name = "Beg"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_beg/blob/master/LICENSE.md"
description = "Beg is Twitter Bootstrap based theme."
tags = ["xjp"]
features = ["blog"]
min_version = 0.15

[author]
    name = "xjp"
    homepage = "http://www.fpstop.com/"

